server {
    listen 80;
    listen [::]:80;
    
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = / {
        return 302 $scheme://$http_host/convert/;
    }

    location /convert/ {
        try_files $uri $uri/ /convert/index.html;
    }
}
