name: Build Electron Releases

on:
  push:
    branches: ["master"]

permissions:
  contents: write

jobs:
  build-electron:
    runs-on: ${{ matrix.os }}

    env:
      VITE_COMMIT_SHA: ${{ github.sha }}

    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            platform: linux
          - os: windows-2025
            platform: win
          - os: macos-15
            platform: mac

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"
          cache: true

      - name: Install dependencies
        run: bun i --frozen-lockfile

      - name: Build Distribution for ${{ matrix.platform }}
        run: bun run desktop:dist:${{ matrix.platform }}

      - name: Publish GitHub Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Rolling Release
          prerelease: true
          overwrite: true
          files: |
            release/*.exe
            release/*.dmg
            release/*.AppImage
            release/*.zip
            release/*.snap
            release/*.deb
          body: "This release contains offline Electron builds of convert.to.it, built from the latest commit on the `master` branch."
